// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwut8k60I2qrCnX1dRKJ-ud_0HZibRdzc',
    appId: '1:137114861482:web:3b7bb5d87a78a304b175d3',
    messagingSenderId: '137114861482',
    projectId: 'yemekapp5678',
    authDomain: 'yemekapp5678.firebaseapp.com',
    storageBucket: 'yemekapp5678.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAf8XVitQNx9KLbCiVcfrVjBje02trvvk',
    appId: '1:137114861482:android:5c858b44587e8727b175d3',
    messagingSenderId: '137114861482',
    projectId: 'yemekapp5678',
    storageBucket: 'yemekapp5678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWFecdtYSbEdSkH7OAza9qfYp1cucA_c',
    appId: '1:137114861482:ios:4fe164cdf8826ca1b175d3',
    messagingSenderId: '137114861482',
    projectId: 'yemekapp5678',
    storageBucket: 'yemekapp5678.appspot.com',
    iosBundleId: 'com.example.yemekUygulamasi',
  );
}
